### ISSUE TITLE
Not work with UE4.23

### ISSUE THREAD

**Issue by AngelTs** [EverNewJoy/VictoryPlugin#65]
1.
error C2248: 'UInputSettings::AxisMappings': cannot access private member declared in class 'UInputSettings'
2.
error C2248: 'UInputSettings::ActionMappings': cannot access private member declared in class 'UInputSettings'

**Comment by saidmoya12** [comment]
IO check it today and work.

Just need build it from Visual Studio downloading the last version!

**Comment by saidmoya12** [comment]
Work with 4.23 if you download and compile the last source code from visual studio.

**Comment by NextWorldVR** [comment]
> Work with 4.23 if you download and compile the last source code from visual studio.

Can you explain how to do this (what you are talking about?)  I can't get it to work with any version, there seems to be zero documentation or anything at all,. ??

**Comment by serhathan** [comment]
> 1> Creating library E:\UE4\Engine\Plugins\Runtime\VictoryBPLibrary\Intermediate\Build\Win64\UE4Editor\Development\VictoryBPLibrary\UE4Editor-VictoryBPLibrary.suppressed.lib and object E:\UE4\Engine\Plugins\Runtime\VictoryBPLibrary\Intermediate\Build\Win64\UE4Editor\Development\VictoryBPLibrary\UE4Editor-VictoryBPLibrary.suppressed.exp
> 1>Module.VictoryBPLibrary.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) struct FThreadSafeStaticStat StatPtr_STAT_PhysSceneWriteLock" (__imp_?StatPtr_STAT_PhysSceneWriteLock@@3u?$FThreadSafeStaticStat@UFStat_STAT_PhysSceneWriteLock@@@@A)
> 1>E:\UE4\Engine\Plugins\Runtime\VictoryBPLibrary\Binaries\Win64\UE4Editor-VictoryBPLibrary.dll : fatal error LNK1120: 1 unresolved externals
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command "....\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
> 1>Done building project "UE4.vcxproj" -- FAILED.

did you resolve?

**Comment by Doublezer0** [comment]
> 
> 
> > 1> Creating library E:\UE4\Engine\Plugins\Runtime\VictoryBPLibrary\Intermediate\Build\Win64\UE4Editor\Development\VictoryBPLibrary\UE4Editor-VictoryBPLibrary.suppressed.lib and object E:\UE4\Engine\Plugins\Runtime\VictoryBPLibrary\Intermediate\Build\Win64\UE4Editor\Development\VictoryBPLibrary\UE4Editor-VictoryBPLibrary.suppressed.exp
> > 1>Module.VictoryBPLibrary.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) struct FThreadSafeStaticStat StatPtr_STAT_PhysSceneWriteLock" (__imp_?StatPtr_STAT_PhysSceneWriteLock@@3u?$FThreadSafeStaticStat@UFStat_STAT_PhysSceneWriteLock@@@@A)
> > 1>E:\UE4\Engine\Plugins\Runtime\VictoryBPLibrary\Binaries\Win64\UE4Editor-VictoryBPLibrary.dll : fatal error LNK1120: 1 unresolved externals
> > 1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command "....\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
> > 1>Done building project "UE4.vcxproj" -- FAILED.
> 
> did you resolve?

This is a linker error which means a module wasn't loaded in the target build file.
